spring:
  application:
    name: GATEWAYSERVICE

  cloud:
    gateway:
      routes:
        - id: CABBOOKINGMICROSERVICE
          uri: lb://CABBOOKINGMICROSERVICE
          predicates:
            - Path=/cabBooking/**
        - id: USERREGISTRATION
          uri: lb://USERREGISTRATION
          predicates:
            - Path=/userRegister/**
        - id: CABADMIN
          uri: lb://CABADMIN
          predicates:
            - Path=/cabadmin/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost

server:
  port: 8988
